# Login into devices, once in ask someone else for any additional tasks 
---
- hosts: ios
  gather_facts: no
  connection: network_cli
  debugger: on_failed
  become: yes
  become_method: enable
  ignore_errors: yes

  vars:
    authentication_provider: normal

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: group_vars/ios/vars.yml

  - name: Set Primary Username and Password
    set_fact:
      remote_user: "{{ creds['username'] }}"
      ansible_ssh_pass: "{{ creds['password'] }}"
    when: authentication_provider == "normal"

  - name: Set Alternate Username and Password
    set_fact:
      remote_user: "{{ alt_creds['username'] }}"
      ansible_ssh_pass: "{{ alt_creds['password'] }}"
    when: authentication_provider == "alternate"

# Want to do anything else? 
  - include: tasks/sample2.yml
