---
- hosts: ios-swt
  gather_facts: no
  connection: local

  tasks:
 
  - name: obtain login credentials
    include_vars: secrets.yml

  - name: obtain vars
    include_vars: vars/vlans-multi.yml

  - name: define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        transport: cli
        
# Deploy VLANs listed in vars/vlans.yml
  - include: tasks/ios_config-l2-multi-vlan.yml
