---
- hosts: ios
  gather_facts: no
  connection: local

  tasks:
 
  - name: obtain login credentials
    include_vars: secrets.yml

  - name: obtain vars
    include_vars: vars/vlan.yml

  - name: define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        transport: cli

# Check if VLAN listed in vars/vlan.yml exists
  - include: tasks/ios_command-vlan-exist-check.yml

# If VLAN Exist:
  - include: tasks/ios_config-vlan-delete.yml
    when: "{{ vlan_exists }}"
